# Generated by Django 2.0.5 on 2018-05-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=25)),
                ('descricao', models.TextField(max_length=100)),
                ('tipo_contrato', models.CharField(choices=[('CLT', 'Pessoa Fisica'), ('PJ', 'Pessoa Jurídica')], max_length=3)),
                ('salario', models.FloatField()),
                ('status', models.BooleanField(default=1)),
            ],
        ),
    ]
