# frozen_string_literal: true

Vagrant.configure('2') do |config|
  config.vm.box = 'hashicorp/bionic64'

  config.vm.provider 'virtualbox' do |v|
    v.memory = 4096
    v.cpus = 4
  end

  config.vm.provision 'ansible' do |a|
    a.playbook = 'local.yml'
  end

  config.vm.network 'private_network', type: 'dhcp'
end
