version: '3'

services:
  zookeeper:
    image: zookeeper:3.7
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  jobmanager:
    image: flink:1.15
    expose:
      - 8081
    ports:
      - 8081:8081
    command:
      - jobmanager

  taskmanager:
    image: flink:1.15
    expose:
      - 6121
      - 6122
      - 6123
      - 6124
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    command: taskmanager

  app:
    build: .
    command: |
      br.com.flaviogf.beam.example3.App
      --runner='FlinkRunner'
      --flinkMaster='jobmanager:8081'
    depends_on:
      - kafka
      - jobmanager
      - taskmanager
