# Generated by Django 2.1.7 on 2019-03-08 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pontoturistico',
            old_name='descricacao',
            new_name='descricao',
        ),
    ]
