version: '3'

services:
  app:
    build:
      context: ./node
    volumes:
      - ./node:/usr/src/app
    ports:
      - 3000:3000
    tty: true
  db:
    image: mysql:8.2
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nodedb
