// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Section5.OrderingQueries;

namespace Section5.OrderingQueries.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20191218184708_seed")]
    partial class seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Section5.OrderingQueries.Models.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("ArtistId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArtistId = 3,
                            Name = "Jacobi, Gottlieb and Tillman"
                        },
                        new
                        {
                            Id = 2,
                            ArtistId = 9,
                            Name = "Bruen, Vandervort and Stoltenberg"
                        },
                        new
                        {
                            Id = 3,
                            ArtistId = 4,
                            Name = "Bernier Inc"
                        },
                        new
                        {
                            Id = 4,
                            ArtistId = 5,
                            Name = "Weimann, Purdy and Beahan"
                        },
                        new
                        {
                            Id = 5,
                            ArtistId = 10,
                            Name = "Reichel, Casper and Ferry"
                        },
                        new
                        {
                            Id = 6,
                            ArtistId = 9,
                            Name = "Krajcik, Schneider and Pouros"
                        },
                        new
                        {
                            Id = 7,
                            ArtistId = 2,
                            Name = "Hauck - Will"
                        },
                        new
                        {
                            Id = 8,
                            ArtistId = 9,
                            Name = "Legros Group"
                        },
                        new
                        {
                            Id = 9,
                            ArtistId = 4,
                            Name = "Wolf Inc"
                        },
                        new
                        {
                            Id = 10,
                            ArtistId = 6,
                            Name = "Deckow - Auer"
                        });
                });

            modelBuilder.Entity("Section5.OrderingQueries.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Emmett Kassulke"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Alyssa Legros"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Allison McDermott"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Madeline Deckow"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Rebecca Dibbert"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Candice Gaylord"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Bessie Gleason"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Helen Schinner"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Mindy Hoeger"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Gerard Berge"
                        });
                });

            modelBuilder.Entity("Section5.OrderingQueries.Models.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AlbumId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("Tracks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlbumId = 1,
                            Name = "Trantow and Sons"
                        },
                        new
                        {
                            Id = 2,
                            AlbumId = 8,
                            Name = "Gerhold - Haag"
                        },
                        new
                        {
                            Id = 3,
                            AlbumId = 2,
                            Name = "Nolan Group"
                        },
                        new
                        {
                            Id = 4,
                            AlbumId = 2,
                            Name = "Becker Group"
                        },
                        new
                        {
                            Id = 5,
                            AlbumId = 6,
                            Name = "Bednar - Howe"
                        },
                        new
                        {
                            Id = 6,
                            AlbumId = 9,
                            Name = "Weber Inc"
                        },
                        new
                        {
                            Id = 7,
                            AlbumId = 4,
                            Name = "Bogisich, Homenick and Bernier"
                        },
                        new
                        {
                            Id = 8,
                            AlbumId = 3,
                            Name = "Bernier - Weissnat"
                        },
                        new
                        {
                            Id = 9,
                            AlbumId = 4,
                            Name = "Schroeder - McCullough"
                        },
                        new
                        {
                            Id = 10,
                            AlbumId = 1,
                            Name = "Hickle - Emmerich"
                        });
                });

            modelBuilder.Entity("Section5.OrderingQueries.Models.Album", b =>
                {
                    b.HasOne("Section5.OrderingQueries.Models.Artist", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Section5.OrderingQueries.Models.Track", b =>
                {
                    b.HasOne("Section5.OrderingQueries.Models.Album", "Album")
                        .WithMany("Tracks")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
