version: '3.9'

services:
  app:
    build: .
    volumes:
      - ./:/usr/local/app
    environment:
      RUBYOPT: '-W0'
  es01:
    image: elasticsearch:7.14.0
    environment:
      discovery.type: 'single-node'
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: kibana:7.14.0
    environment:
      ELASTICSEARCH_HOSTS: 'http://es01:9200'
    ports:
      - 5601:5601
