version: '3.9'

services:
  web:
    build: .
    command: ['bin/rails', 's', '-b', '0.0.0.0']
    ports:
      - 3001:3000
    volumes:
      - ./:/www
    tty: true
    stdin_open: true
  chrome:
    image: selenium/standalone-chrome-debug
    ports:
      - 5900:5900
    shm_size: 2gb
