CREATE TABLE permissions(
    id BIGINT(20) PRIMARY KEY,
    description VARCHAR(255) NOT NULL
) Engine=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO permissions VALUES(1, "ROLE_CREATE_CATEGORY");
INSERT INTO permissions VALUES(2, "ROLE_READ_CATEGORY");
INSERT INTO permissions VALUES(3, "ROLE_CREATE_PERSON");
INSERT INTO permissions VALUES(4, "ROLE_DELETE_PERSON");
INSERT INTO permissions VALUES(5, "ROLE_READ_PERSON");
INSERT INTO permissions VALUES(6, "ROLE_CREATE_TRANSACTION");
INSERT INTO permissions VALUES(7, "ROLE_DELETE_TRANSACTION");
INSERT INTO permissions VALUES(8, "ROLE_READ_TRANSACTION");
