//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Section10.GeneratingCode {
    using System;
    
    
    public class Employe {
        
        public string Name;
        
        public int Salary;
        
        public Employe(string name, int salary) {
            Name = name;
            Salary = salary;
        }
    }
}
