// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Section6.CountingAndTotalizing;

namespace Section6.CountingAndTotalizing.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20191224144517_seed")]
    partial class seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("Section6.CountingAndTotalizing.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArtistId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArtistId = 4,
                            Title = "Explicabo sed sint."
                        },
                        new
                        {
                            Id = 2,
                            ArtistId = 9,
                            Title = "Mollitia sunt aperiam vero et aperiam reiciendis."
                        },
                        new
                        {
                            Id = 3,
                            ArtistId = 4,
                            Title = "Debitis ut aliquid mollitia quo ipsam vel ea."
                        },
                        new
                        {
                            Id = 4,
                            ArtistId = 6,
                            Title = "Mollitia quidem quo nisi ea."
                        },
                        new
                        {
                            Id = 5,
                            ArtistId = 2,
                            Title = "Culpa aut est exercitationem qui inventore."
                        },
                        new
                        {
                            Id = 6,
                            ArtistId = 5,
                            Title = "Ab quae nesciunt praesentium mollitia optio vel repudiandae vitae dolor."
                        },
                        new
                        {
                            Id = 7,
                            ArtistId = 8,
                            Title = "Voluptatem rem nostrum maxime est maxime est."
                        },
                        new
                        {
                            Id = 8,
                            ArtistId = 2,
                            Title = "Aut placeat cum quis dolor blanditiis quia quasi in illo."
                        },
                        new
                        {
                            Id = 9,
                            ArtistId = 10,
                            Title = "Id temporibus enim eius."
                        },
                        new
                        {
                            Id = 10,
                            ArtistId = 6,
                            Title = "Sunt numquam est harum dolorem molestiae aut esse odit."
                        });
                });

            modelBuilder.Entity("Section6.CountingAndTotalizing.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Georgia Rohan"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Kristy Bergnaum"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bryan Blick"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Shelley Cartwright"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Myra Schuppe"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Deborah Jaskolski"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Jerome McLaughlin"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Erik Kuvalis"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Marcia Rowe"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Rickey Thompson"
                        });
                });

            modelBuilder.Entity("Section6.CountingAndTotalizing.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlbumId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("Tracks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlbumId = 5,
                            Name = "Est architecto velit.",
                            Price = 10516
                        },
                        new
                        {
                            Id = 2,
                            AlbumId = 3,
                            Name = "Ullam atque quia esse.",
                            Price = 12077
                        },
                        new
                        {
                            Id = 3,
                            AlbumId = 10,
                            Name = "Nobis quia aliquam esse esse soluta voluptatem cupiditate placeat.",
                            Price = 10758
                        },
                        new
                        {
                            Id = 4,
                            AlbumId = 7,
                            Name = "Numquam dolore culpa placeat ipsam omnis ut.",
                            Price = 10380
                        },
                        new
                        {
                            Id = 5,
                            AlbumId = 4,
                            Name = "Reiciendis voluptas quod iste dolorum ut id assumenda ea.",
                            Price = 10072
                        },
                        new
                        {
                            Id = 6,
                            AlbumId = 4,
                            Name = "Hic quae tempore natus alias nihil dolores molestias vero odit.",
                            Price = 19305
                        },
                        new
                        {
                            Id = 7,
                            AlbumId = 2,
                            Name = "Et quisquam minus vero expedita necessitatibus omnis aut saepe.",
                            Price = 14901
                        },
                        new
                        {
                            Id = 8,
                            AlbumId = 4,
                            Name = "Vero veritatis ab temporibus reiciendis laborum maxime quas.",
                            Price = 12973
                        },
                        new
                        {
                            Id = 9,
                            AlbumId = 9,
                            Name = "Beatae possimus possimus molestiae neque provident recusandae.",
                            Price = 14309
                        },
                        new
                        {
                            Id = 10,
                            AlbumId = 1,
                            Name = "Porro optio magnam alias voluptates nihil odio blanditiis architecto.",
                            Price = 19036
                        });
                });

            modelBuilder.Entity("Section6.CountingAndTotalizing.Album", b =>
                {
                    b.HasOne("Section6.CountingAndTotalizing.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Section6.CountingAndTotalizing.Track", b =>
                {
                    b.HasOne("Section6.CountingAndTotalizing.Album", "Album")
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
