// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Section6.CountingAndTotalizing;

namespace Section6.CountingAndTotalizing.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Section6.CountingAndTotalizing.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArtistId = 7,
                            Title = "Dolorem animi et minus tempora error."
                        },
                        new
                        {
                            Id = 2,
                            ArtistId = 7,
                            Title = "Officiis sit eum nemo magnam occaecati."
                        },
                        new
                        {
                            Id = 3,
                            ArtistId = 10,
                            Title = "Et error et ut."
                        },
                        new
                        {
                            Id = 4,
                            ArtistId = 9,
                            Title = "Et perspiciatis accusamus."
                        },
                        new
                        {
                            Id = 5,
                            ArtistId = 9,
                            Title = "Asperiores voluptatem ab quaerat."
                        },
                        new
                        {
                            Id = 6,
                            ArtistId = 1,
                            Title = "Nulla doloribus odio commodi aut et porro rerum dignissimos."
                        },
                        new
                        {
                            Id = 7,
                            ArtistId = 9,
                            Title = "Voluptatem perspiciatis eveniet earum dolores."
                        },
                        new
                        {
                            Id = 8,
                            ArtistId = 4,
                            Title = "Veniam eius provident nihil impedit ex aliquam et."
                        },
                        new
                        {
                            Id = 9,
                            ArtistId = 5,
                            Title = "Nam corporis dolorem quasi dolores odio."
                        },
                        new
                        {
                            Id = 10,
                            ArtistId = 1,
                            Title = "Sed dolor consequatur voluptas itaque vel unde."
                        });
                });

            modelBuilder.Entity("Section6.CountingAndTotalizing.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Clay Block"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Jerome Morissette"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Victoria McDermott"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Travis Mills"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Gerald Dicki"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Jan Pagac"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Shannon Runolfsson"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Stacy Gorczany"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Adam Boyer"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Sadie Senger"
                        });
                });

            modelBuilder.Entity("Section6.CountingAndTotalizing.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("TrackId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrackId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 15960,
                            Quantity = 142,
                            TrackId = 7
                        },
                        new
                        {
                            Id = 2,
                            Price = 14712,
                            Quantity = 137,
                            TrackId = 9
                        },
                        new
                        {
                            Id = 3,
                            Price = 10105,
                            Quantity = 124,
                            TrackId = 2
                        },
                        new
                        {
                            Id = 4,
                            Price = 12271,
                            Quantity = 141,
                            TrackId = 7
                        },
                        new
                        {
                            Id = 5,
                            Price = 10285,
                            Quantity = 167,
                            TrackId = 10
                        },
                        new
                        {
                            Id = 6,
                            Price = 12781,
                            Quantity = 116,
                            TrackId = 10
                        },
                        new
                        {
                            Id = 7,
                            Price = 10839,
                            Quantity = 118,
                            TrackId = 8
                        },
                        new
                        {
                            Id = 8,
                            Price = 14528,
                            Quantity = 108,
                            TrackId = 8
                        },
                        new
                        {
                            Id = 9,
                            Price = 17971,
                            Quantity = 199,
                            TrackId = 4
                        },
                        new
                        {
                            Id = 10,
                            Price = 17980,
                            Quantity = 152,
                            TrackId = 1
                        });
                });

            modelBuilder.Entity("Section6.CountingAndTotalizing.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlbumId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("Tracks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlbumId = 5,
                            Name = "Tempora voluptas rerum tempora dolores laboriosam ea aut nam suscipit.",
                            Price = 12792
                        },
                        new
                        {
                            Id = 2,
                            AlbumId = 4,
                            Name = "Odit et esse.",
                            Price = 12235
                        },
                        new
                        {
                            Id = 3,
                            AlbumId = 5,
                            Name = "Dolore velit qui aut.",
                            Price = 14080
                        },
                        new
                        {
                            Id = 4,
                            AlbumId = 9,
                            Name = "Accusantium debitis occaecati veniam sequi.",
                            Price = 16662
                        },
                        new
                        {
                            Id = 5,
                            AlbumId = 5,
                            Name = "Doloremque ut odio ipsum ipsum delectus.",
                            Price = 10963
                        },
                        new
                        {
                            Id = 6,
                            AlbumId = 5,
                            Name = "Odit voluptatibus aliquam quia tempore similique ut dolorum sequi.",
                            Price = 17941
                        },
                        new
                        {
                            Id = 7,
                            AlbumId = 2,
                            Name = "Ea modi qui illum sed enim deleniti qui eum.",
                            Price = 15493
                        },
                        new
                        {
                            Id = 8,
                            AlbumId = 8,
                            Name = "Optio beatae nihil aut ratione illo ipsum.",
                            Price = 11044
                        },
                        new
                        {
                            Id = 9,
                            AlbumId = 9,
                            Name = "Repellat excepturi sequi ipsum aliquid enim quia nam repellat laudantium.",
                            Price = 16165
                        },
                        new
                        {
                            Id = 10,
                            AlbumId = 10,
                            Name = "Ipsam doloribus aliquid delectus et maiores facilis qui.",
                            Price = 14315
                        });
                });

            modelBuilder.Entity("Section6.CountingAndTotalizing.Album", b =>
                {
                    b.HasOne("Section6.CountingAndTotalizing.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Section6.CountingAndTotalizing.Item", b =>
                {
                    b.HasOne("Section6.CountingAndTotalizing.Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Section6.CountingAndTotalizing.Track", b =>
                {
                    b.HasOne("Section6.CountingAndTotalizing.Album", "Album")
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
