// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Section6.CountingAndTotalizing;

namespace Section6.CountingAndTotalizing.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("Section6.CountingAndTotalizing.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArtistId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArtistId = 2,
                            Title = "Harum ratione fugit aliquid."
                        },
                        new
                        {
                            Id = 2,
                            ArtistId = 1,
                            Title = "Ut et id qui."
                        },
                        new
                        {
                            Id = 3,
                            ArtistId = 7,
                            Title = "Explicabo sapiente alias omnis cumque dignissimos reiciendis in dolores culpa."
                        },
                        new
                        {
                            Id = 4,
                            ArtistId = 9,
                            Title = "Voluptas reprehenderit aut vel ullam consequuntur sit."
                        },
                        new
                        {
                            Id = 5,
                            ArtistId = 1,
                            Title = "In odio delectus."
                        },
                        new
                        {
                            Id = 6,
                            ArtistId = 3,
                            Title = "Tenetur hic qui veritatis earum aut qui quibusdam porro placeat."
                        },
                        new
                        {
                            Id = 7,
                            ArtistId = 1,
                            Title = "Rerum doloremque voluptate."
                        },
                        new
                        {
                            Id = 8,
                            ArtistId = 7,
                            Title = "Illo excepturi provident excepturi minus aliquam est magni."
                        },
                        new
                        {
                            Id = 9,
                            ArtistId = 1,
                            Title = "Qui et eligendi cupiditate."
                        },
                        new
                        {
                            Id = 10,
                            ArtistId = 7,
                            Title = "Est corrupti doloremque rerum iusto quidem dolorum omnis ipsa."
                        });
                });

            modelBuilder.Entity("Section6.CountingAndTotalizing.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Christie Corkery"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Jonathon McDermott"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dean VonRueden"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Kim McKenzie"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Flora Bogan"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ian Rice"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Andres Boehm"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Louise Lebsack"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Tommie Abbott"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Ralph Krajcik"
                        });
                });

            modelBuilder.Entity("Section6.CountingAndTotalizing.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrackId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TrackId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Quantity = 106,
                            TrackId = 2
                        },
                        new
                        {
                            Id = 2,
                            Quantity = 131,
                            TrackId = 7
                        },
                        new
                        {
                            Id = 3,
                            Quantity = 122,
                            TrackId = 5
                        },
                        new
                        {
                            Id = 4,
                            Quantity = 198,
                            TrackId = 8
                        },
                        new
                        {
                            Id = 5,
                            Quantity = 145,
                            TrackId = 6
                        },
                        new
                        {
                            Id = 6,
                            Quantity = 104,
                            TrackId = 7
                        },
                        new
                        {
                            Id = 7,
                            Quantity = 117,
                            TrackId = 5
                        },
                        new
                        {
                            Id = 8,
                            Quantity = 155,
                            TrackId = 1
                        },
                        new
                        {
                            Id = 9,
                            Quantity = 110,
                            TrackId = 3
                        },
                        new
                        {
                            Id = 10,
                            Quantity = 162,
                            TrackId = 8
                        });
                });

            modelBuilder.Entity("Section6.CountingAndTotalizing.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlbumId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("Tracks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlbumId = 5,
                            Name = "Deserunt incidunt corrupti voluptatem.",
                            Price = 19814
                        },
                        new
                        {
                            Id = 2,
                            AlbumId = 4,
                            Name = "Eum qui corrupti laudantium modi eligendi qui non.",
                            Price = 17972
                        },
                        new
                        {
                            Id = 3,
                            AlbumId = 1,
                            Name = "Debitis accusantium tempora amet nemo sint perspiciatis autem.",
                            Price = 12378
                        },
                        new
                        {
                            Id = 4,
                            AlbumId = 9,
                            Name = "Saepe assumenda rem inventore quia dolores.",
                            Price = 11220
                        },
                        new
                        {
                            Id = 5,
                            AlbumId = 2,
                            Name = "Eligendi itaque delectus.",
                            Price = 15859
                        },
                        new
                        {
                            Id = 6,
                            AlbumId = 4,
                            Name = "Voluptatem ut suscipit eius molestias.",
                            Price = 18242
                        },
                        new
                        {
                            Id = 7,
                            AlbumId = 5,
                            Name = "Neque est ut.",
                            Price = 19230
                        },
                        new
                        {
                            Id = 8,
                            AlbumId = 10,
                            Name = "Est architecto necessitatibus corrupti delectus natus quisquam.",
                            Price = 11640
                        },
                        new
                        {
                            Id = 9,
                            AlbumId = 1,
                            Name = "Mollitia doloremque numquam minus maiores earum veritatis.",
                            Price = 16001
                        },
                        new
                        {
                            Id = 10,
                            AlbumId = 9,
                            Name = "Expedita minima ipsa.",
                            Price = 17299
                        });
                });

            modelBuilder.Entity("Section6.CountingAndTotalizing.Album", b =>
                {
                    b.HasOne("Section6.CountingAndTotalizing.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Section6.CountingAndTotalizing.Item", b =>
                {
                    b.HasOne("Section6.CountingAndTotalizing.Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Section6.CountingAndTotalizing.Track", b =>
                {
                    b.HasOne("Section6.CountingAndTotalizing.Album", "Album")
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
