// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Section10.CreateAndApplyAttributes;

namespace Section10.CreateAndApplyAttributes.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20191126115429_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1");

            modelBuilder.Entity("Section10.CreateAndApplyAttributes.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 1000,
                            Date = new DateTime(2019, 11, 21, 8, 54, 29, 183, DateTimeKind.Local).AddTicks(7375)
                        },
                        new
                        {
                            Id = 2,
                            Amount = 10000,
                            Date = new DateTime(2019, 11, 26, 8, 54, 29, 187, DateTimeKind.Local).AddTicks(2554)
                        },
                        new
                        {
                            Id = 3,
                            Amount = 100000,
                            Date = new DateTime(2019, 12, 1, 8, 54, 29, 187, DateTimeKind.Local).AddTicks(2601)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
