---
- name: Provision VM
  hosts: all
  become: yes
  remote_user: ubuntu
  tasks:
    - name: Ping
      ping:
    - name: Install Minikube
      ansible.builtin.get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        dest: /usr/local/bin/minikube
        mode: '0755'
    - name: Install Docker's dependencies
      ansible.builtin.apt:
        update_cache: yes
        pkg:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
    - name: Install Docker's official GPG
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/trusted.gpg.d/docker.asc
    - name: Add Docker's repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/ubuntu xenial stable"
        filename: docker
    - name: Install Docker
      ansible.builtin.apt:
        update_cache: yes
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
