// <auto-generated />
namespace CursoAspNetMvc5Alura.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Cliente_Data_Cadastro : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Cliente_Data_Cadastro));
        
        string IMigrationMetadata.Id
        {
            get { return "201808182031589_Cliente_Data_Cadastro"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
