version: '3.9'

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    environment:
      cluster.name: es-docker-cluster
      discovery.type: single-node
      node.name: es01
    ports:
      - 9200:9200
      - 9300:9300
