// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Section7.MaxMinAverageAndExtensionMethods;

namespace Section7.MaxMinAverageAndExtensionMethods.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20191224195914_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Section7.MaxMinAverageAndExtensionMethods.Employe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Employes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Flavio",
                            Salary = 500m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fernando",
                            Salary = 5000m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fatima",
                            Salary = 5000m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Luis Fernando",
                            Salary = 15000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
