# frozen_string_literal: true

Vagrant.configure('2') do |config|
  config.vm.box = 'hashicorp/bionic64'

  config.vm.provider 'virtualbox' do |v|
    v.memory = '2048'
    v.cpus = 2
  end

  config.vm.provision 'ansible' do |ansible|
    ansible.playbook = 'local.yml'
  end
end
