version: '3.9'

services:
  app:
    build: .
    environment:
      JAEGER_ENDPOINT: 'http://jaeger:14268/api/traces'
      SERVICE_NAME: 'hello-world'
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 16686:16686
