kind: Deployment
apiVersion: apps/v1

metadata:
  name: go-server
  labels:
    app: go-server

spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-server
  template:
    metadata:
      labels:
        app: go-server
    spec:
      containers:
      - name: go-server
        image: flaviogf/fullcycle-kubernetes:0.0.6
        envFrom:
          - configMapRef:
              name: go-server-config
          - secretRef:
              name: go-server-secret
        volumeMounts:
          - name: config-volume
            mountPath: /etc/config
            readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: go-server-config
            items:
              - key: CLUSTER_ENDPOINTS
                path: cluster_endpoints
