# Generated by Django 2.1.7 on 2019-03-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atracao',
            name='nome',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
