Vagrant.configure("2") do |config|
    config.vm.define "web" do |web|
      web.vm.provision "shell", inline: <<-SHELL
        echo Updating!!!
        sudo apt-get update
        echo Installing puppet!!!
        sudo apt-get install -y puppet
      SHELL
      web.vm.box = "hashicorp/precise32"
      web.vm.network "private_network", ip: "192.168.50.10"
    end
end
