Vagrant.configure("2") do |config|
    config.vm.define "app" do |app|
      app.vm.box = "ubuntu/xenial64"

      app.vm.network "private_network", ip: "192.168.50.10"

      app.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update

        sudo apt-get upgrade

        sudo apt-get install -y puppet
      SHELL

      app.vm.provision "puppet" do |puppet|
        puppet.manifest_file = "app.pp"
      end
    end
end
