version: '3.9'

services:
  app:
    build: .
    volumes:
      - ./:/usr/local/app
  db:
    image: postgres:9.6.2-alpine
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: seven_dbs
