version: '3.9'

services:
  app:
    build: .
    volumes:
      - ./:/usr/local/app
    environment:
      MONGOID_ENV: development
  db:
    image: mongo:3.2.20
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: mongodb
