Vagrant.configure('2') do |config|
  config.vm.box = 'hashicorp/bionic64'
  config.vm.provision :shell, inline: SCRIPT
end

SCRIPT = <<-SCRIPT

if ! grep -q 'export PATH="$PATH:/usr/local/go/bin"' /home/vagrant/.bashrc; then
  echo 'export PATH="$PATH:/usr/local/go/bin"' >> /home/vagrant/.bashrc
fi

if ! grep -q 'export PATH="$PATH:$(go env GOPATH)/bin"' /home/vagrant/.bashrc; then
  echo 'export PATH="$PATH:$(go env GOPATH)/bin"' >> /home/vagrant/.bashrc
fi

apt install -y unzip

rm -rf /usr/local/go
curl -L -o /tmp/go.tar.gz https://golang.org/dl/go1.16.4.linux-amd64.tar.gz
tar -C /usr/local -xzf /tmp/go.tar.gz

curl -L -o /tmp/protoc.zip https://github.com/protocolbuffers/protobuf/releases/download/v3.15.8/protoc-3.15.8-linux-x86_64.zip
unzip /tmp/protoc.zip -d /usr/local
chmod 777 /usr/local/bin/protoc

SCRIPT
