# Generated by Django 2.1.5 on 2019-01-26 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='nome')),
                ('telefone', models.CharField(max_length=250, verbose_name='telefone')),
                ('empresa', models.CharField(max_length=250, verbose_name='empresa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado_em')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
                'ordering': ['nome'],
            },
        ),
    ]
