SELECT * FROM [TABELA DE PRODUTOS] WHERE [SABOR] = 'UVA';

SELECT * FROM [TABELA DE PRODUTOS] WHERE [PREÇO DE LISTA] = 4.555;

SELECT * FROM [TABELA DE PRODUTOS] WHERE [PREÇO DE LISTA] > 10;

SELECT * FROM [TABELA DE PRODUTOS] WHERE [EMBALAGEM] <> 'LATA';

SELECT * FROM [TABELA DE CLIENTES] WHERE [DATA DE NASCIMENTO] = '1995-09-11';

SELECT * FROM [TABELA DE CLIENTES] WHERE [DATA DE NASCIMENTO] > '1995-09-11';

SELECT * FROM [TABELA DE PRODUTOS] WHERE [SABOR] = 'MANGA' OR [TAMANHO] = '700 ML';

SELECT * FROM [TABELA DE PRODUTOS] WHERE NOT ([SABOR] = 'MANGA' OR [TAMANHO] = '700 ML');

SELECT * FROM [TABELA DE PRODUTOS] WHERE [SABOR] IN ('MANGA', 'LARANJA');

SELECT * FROM [TABELA DE PRODUTOS] WHERE [SABOR] NOT IN ('MANGA', 'LARANJA');

SELECT * FROM [TABELA DE PRODUTOS] WHERE [NOME DO PRODUTO] LIKE '%LITROS%';

SELECT * FROM [TABELA DE PRODUTOS] WHERE [NOME DO PRODUTO] LIKE 'LINHA%';

SELECT [EMBALAGEM], [TAMANHO] FROM [TABELA DE PRODUTOS];

SELECT DISTINCT [EMBALAGEM], [TAMANHO] FROM [TABELA DE PRODUTOS];

SELECT DISTINCT [EMBALAGEM], [TAMANHO] FROM [TABELA DE PRODUTOS] WHERE [SABOR] = 'LARANJA';

SELECT TOP 3 * FROM [TABELA DE PRODUTOS];

SELECT TOP 3 * FROM [TABELA DE PRODUTOS] WHERE [SABOR] = 'LARANJA';

SELECT DISTINCT TOP 3 [EMBALAGEM], [TAMANHO] FROM [TABELA DE PRODUTOS];

SELECT * FROM [TABELA DE PRODUTOS] ORDER BY [PREÇO DE LISTA];

SELECT * FROM [TABELA DE PRODUTOS] ORDER BY [PREÇO DE LISTA] DESC;

SELECT * FROM [TABELA DE PRODUTOS] ORDER BY [NOME DO PRODUTO];

SELECT [EMBALAGEM], [NOME DO PRODUTO] FROM [TABELA DE PRODUTOS] ORDER BY [EMBALAGEM], [NOME DO PRODUTO];

SELECT [ESTADO], [LIMITE DE CREDITO] FROM [TABELA DE CLIENTES];

SELECT [ESTADO], SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] GROUP BY [ESTADO];

SELECT [ESTADO], AVG([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] GROUP BY [ESTADO];

SELECT [EMBALAGEM], MAX([PREÇO DE LISTA]) FROM [TABELA DE PRODUTOS] GROUP BY [EMBALAGEM];

SELECT [EMBALAGEM], MIN([PREÇO DE LISTA]) FROM [TABELA DE PRODUTOS] GROUP BY [EMBALAGEM];

SELECT [EMBALAGEM], COUNT(*) FROM [TABELA DE PRODUTOS] GROUP BY [EMBALAGEM];

SELECT [BAIRRO], [ESTADO], SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] WHERE [ESTADO] = 'SP' GROUP BY [BAIRRO], [ESTADO];

SELECT [BAIRRO], SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] GROUP BY [BAIRRO] HAVING SUM([LIMITE DE CREDITO]) > 140000;

SELECT [ESTADO], SUM([LIMITE DE CREDITO]) FROM [DBO].[TABELA DE CLIENTES] GROUP BY [ESTADO] HAVING SUM([LIMITE DE CREDITO]) > 850000;

SELECT [NOME DO PRODUTO], 
CASE
	WHEN [PREÇO DE LISTA] >= 12 THEN 'PRODUTO CARO'
	WHEN [PREÇO DE LISTA] >= 7 THEN 'PRODUTO EM CONTA'
	ELSE 'PRODUTO BARATO'
END AS CONDICAO,
[PREÇO DE LISTA]
FROM [TABELA DE PRODUTOS];

SELECT YEAR([DATA DE NASCIMENTO]), COUNT(*) FROM [TABELA DE CLIENTES] GROUP BY YEAR([DATA DE NASCIMENTO]);