version: "3.9"

services:
  app:
    build: .
    volumes:
      - ./:/usr/local/app
  elasticsearch:
    image: elasticsearch:7.13.4
    environment:
      discovery.type: "single-node"
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: kibana:7.13.4
    ports:
      - 5601:5601
