# frozen_string_literal: true

task :health do
  ruby 'bin/health'
end

task :stats do
  ruby 'bin/stats'
end

task :create_favorite_candy_index do
  ruby 'bin/create_favorite_candy_index'
end

task :index_document do
  ruby 'bin/index_document'
end

task :read_document do
  ruby 'bin/read_document'
end
