# Generated by Django 2.0.5 on 2018-05-14 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de início')),
                ('imagem', models.ImageField(upload_to='curso/imagem', verbose_name='Imagem')),
                ('criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('atualizacao', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
            ],
        ),
    ]
