# Generated by Django 2.0.5 on 2018-05-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_auto_20180513_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='cursos/imagem', verbose_name='Imagem'),
        ),
    ]
