using System.Web;

namespace BuildingCustomHttpHandler.Handlers
{
    public class SampleHttpHandler : IHttpHandler
    {
        public bool IsReusable => false;

        public void ProcessRequest(HttpContext context)
        {
            context.Response.Write($"This message was generated by {nameof(SampleHttpHandler)}!");
        }
    }
}