// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Section4.AssociatingAndFilteringTheModelEntities;

namespace Section4.AssociatingAndFilteringTheModelEntities.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20191218155146_insert_albums")]
    partial class insert_albums
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Section4.AssociatingAndFilteringTheModelEntities.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("ArtistId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArtistId = 8,
                            Name = "Sue Morissette"
                        },
                        new
                        {
                            Id = 2,
                            ArtistId = 2,
                            Name = "Christopher Daugherty"
                        },
                        new
                        {
                            Id = 3,
                            ArtistId = 9,
                            Name = "Henrietta Braun"
                        },
                        new
                        {
                            Id = 4,
                            ArtistId = 4,
                            Name = "Josefina Stamm"
                        },
                        new
                        {
                            Id = 5,
                            ArtistId = 8,
                            Name = "Shaun Shields"
                        },
                        new
                        {
                            Id = 6,
                            ArtistId = 7,
                            Name = "Pamela Renner"
                        },
                        new
                        {
                            Id = 7,
                            ArtistId = 3,
                            Name = "Kerry Wolf"
                        },
                        new
                        {
                            Id = 8,
                            ArtistId = 6,
                            Name = "Betty Terry"
                        },
                        new
                        {
                            Id = 9,
                            ArtistId = 1,
                            Name = "Lucille Wehner"
                        },
                        new
                        {
                            Id = 10,
                            ArtistId = 1,
                            Name = "Dianne Altenwerth"
                        });
                });

            modelBuilder.Entity("Section4.AssociatingAndFilteringTheModelEntities.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Beatrice Maggio"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Miguel Moore"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ricardo McClure"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Elmer Schaden"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Leslie Collins"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Shelley Lueilwitz"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Alfredo Hettinger"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Iris Bahringer"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Roxanne Pacocha"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Blanche Klein"
                        });
                });

            modelBuilder.Entity("Section4.AssociatingAndFilteringTheModelEntities.Album", b =>
                {
                    b.HasOne("Section4.AssociatingAndFilteringTheModelEntities.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
