# frozen_string_literal: true

Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/focal64'
  config.vm.hostname = 'dftd'

  config.vm.network('private_network', type: 'dhcp')

  config.vm.provider('virtualbox') do |vb|
    vb.memory = '1024'
    vb.name = 'dftd'
  end

  config.vm.provision('ansible') do |ansible|
    ansible.playbook = 'ansible/site.yml'
  end
end
