# Generated by Django 2.0.5 on 2018-05-14 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='imagem',
            field=models.ImageField(upload_to='cursos/imagem', verbose_name='Imagem'),
        ),
    ]
