CREATE DATABASE VENDA_SUCOS_1;
GO

USE VENDA_SUCOS_1;

CREATE TABLE [TABELA DE CLIENTES]
(
	[CPF] [VARCHAR] (11),
	[NOME] [VARCHAR] (50),
	[ENDERECO1] [VARCHAR] (50),
	[ENDERECO2] [VARCHAR] (50),
	[DATA DE NASCIMENTO] [DATE],
	[IDADE] [SMALLINT],
	[SEXO] [VARCHAR] (2),
	[LIMITE DE CREDITO] [MONEY],
	[VOLUME DE COMPRA] [FLOAT],
	[PRIMEIRA COMPRA] [BIT]
);

CREATE TABLE [TABELA DE VENDEDORES]
(
	[MATRICULA] [VARCHAR] (5),
	[NOME] [VARCHAR] (100),
	[PERCENTUAL COMISSAO] [FLOAT]
);

CREATE TABLE [TABELA DE PRODUTOS]
(
	[CODIGO DO PRODUTO] [VARCHAR] (10),
	[NOME DO PRODUTO] [VARCHAR] (50),
	[EMBALAGEM] [VARCHAR] (20),
	[SABOR] [VARCHAR] (20),
	[PRECO DA LISTA] SMALLMONEY
);

INSERT INTO [TABELA DE PRODUTOS]
(
	[CODIGO DO PRODUTO],
	[NOME DO PRODUTO],
	[EMBALAGEM],
	[SABOR],
	[PRECO DA LISTA]
)
VALUES
(
	'1040107',
	'Light',
	'350 ml',
	'Melância',
	4.56
);

UPDATE [TABELA DE PRODUTOS] SET
[EMBALAGEM] = 'Lata',
[NOME DO PRODUTO] = 'Light 350 ml'
WHERE [CODIGO DO PRODUTO] = '1040107';

DELETE [TABELA DE PRODUTOS] WHERE [CODIGO DO PRODUTO] = '1040107';

INSERT INTO [TABELA DE VENDEDORES]
(
	[MATRICULA],
	[NOME],
	[PERCENTUAL COMISSAO]
)
VALUES
(
	'00233',
	'JOSÉ GERALDO DA FONSECA',
	0.10
);

DELETE [TABELA DE VENDEDORES] WHERE [MATRICULA] = '00233';

ALTER TABLE [TABELA DE PRODUTOS]
ALTER COLUMN [CODIGO DO PRODUTO]
[VARCHAR] (10) NOT NULL;

ALTER TABLE [TABELA DE PRODUTOS]
ADD CONSTRAINT PK_TABELA_DE_PRODUTOS PRIMARY KEY ([CODIGO DO PRODUTO]);

ALTER TABLE [TABELA DE VENDEDORES]
ALTER COLUMN [MATRICULA]
[VARCHAR] (5) NOT NULL;

ALTER TABLE [TABELA DE VENDEDORES]
ADD CONSTRAINT PK_TABELA_DE_VENDEDORS PRIMARY KEY ([MATRICULA]);

SELECT * FROM [TABELA DE CLIENTES];
SELECT * FROM [TABELA DE PRODUTOS];
SELECT * FROM [TABELA DE VENDEDORES];

DROP DATABASE VENDA_SUCOS_1;
