SELECT 
	TOP(3)
	[NOME] 'CLIENTE',
	[CPF] 'DOCUMENTO'
	FROM [TABELA DE CLIENTES];

SELECT * FROM [TABELA DE PRODUTOS];

SELECT
	[NOME DO PRODUTO]
	FROM [TABELA DE PRODUTOS]
	WHERE [SABOR] LIKE '%Limão';

SELECT
	[NOME DO PRODUTO] 'NOME',
	[PREÇO DE LISTA] 'PRECO'
	FROM [TABELA DE PRODUTOS]
	WHERE [PREÇO DE LISTA] > 10;

SELECT
	[NOME],
	[DATA DE NASCIMENTO]
	FROM [TABELA DE CLIENTES] WHERE YEAR([DATA DE NASCIMENTO]) > 1994;

SELECT
	[NOME],
	[DATA DE NASCIMENTO]
	FROM [TABELA DE CLIENTES] WHERE [DATA DE NASCIMENTO] = '1995-10-07';

SELECT
	[NOME],
	[DATA DE NASCIMENTO]
	FROM [TABELA DE CLIENTES] WHERE MONTH([DATA DE NASCIMENTO]) = 6;
