IF OBJECT_ID(N'TABELA DE TESTE', 'U') IS NOT NULL
	BEGIN
		DROP TABLE [TABELA DE TESTE]
		PRINT 'DROPANDO TABELA'
	END

CREATE TABLE [TABELA DE TESTE] (ID INT IDENTITY(1,1))
PRINT 'CRIANDO TABELA'

DECLARE @VALOR_LIMITE INT = 180000000

IF (SELECT SUM(INF.[PREÇO]) FROM [dbo].[NOTAS FISCAIS] NF
	INNER JOIN [dbo].[ITENS NOTAS FISCAIS] INF
	ON NF.[NUMERO] = INF.[NUMERO]) < @VALOR_LIMITE
	PRINT 'VALOR DE COMPRA BAIXO'
ELSE
	PRINT 'VALOR DE CONTA ALTO'
