version: '3.9'

services:
  app:
    build: .
    volumes:
      - ./:/usr/local/app
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    ports:
      - 8200:9200
      - 8300:9300
    environment:
      discovery.type: 'single-node'
  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.0
    ports:
      - 8400:5601
    environment:
      ELASTICSEARCH_HOSTS: 'http://elasticsearch:9200'
