# frozen_string_literal: true

task :create_new_index do
  ruby './bin/create_new_index'
end

task :reindex do
  ruby './bin/reindex'
end

task :remove_negative_values do
  ruby './bin/remove_negative_values'
end
