# frozen_string_literal: true

task :create_new_index do
  ruby './bin/create_new_index'
end

task :reindex do
  ruby './bin/reindex'
end

task :remove_negative_values do
  ruby './bin/remove_negative_values'
end

task :remove_values_greater_than_500 do
  ruby './bin/remove_values_greater_than_500'
end

task :get_information_about_documents do
  ruby './bin/get_information_about_documents'
end

task :unit_price_sum do
  ruby './bin/unit_price_sum'
end

task :lowest_unit_price do
  ruby './bin/lowest_unit_price'
end

task :highest_unit_price do
  ruby './bin/highest_unit_price'
end

task :unit_price_avg do
  ruby './bin/unit_price_avg'
end

task :unit_price_stats do
  ruby './bin/unit_price_stats'
end

task :cardinality do
  ruby './bin/cardinality'
end
