version: '3'

services:
  big_brother:
    build: .
    command: ./big_brother
    environment:
      DB_DRIVER: "postgres"
      DB_DATASOURCE: "dbname=big_brother_db host=big_brother_db user=postgres password=postgres sslmode=disable"
    ports:
      - 8080:80
  formatter:
    build: .
    command: ./formatter
    ports:
      - 8081:80
  big_brother_db:
    image: postgres
    environment:
      POSTGRES_DB: "big_brother_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
