version: '3.9'

services:
  hello:
    build: .
    ports:
      - 8087:80
  db:
    image: postgres
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
