create database webapp;

create table newsletter (id serial, email varchar(250), created_at timestamp without time zone, updated_at timestamp without time zone);

create table category (id serial, name varchar(250), description text, created_at timestamp without time zone, updated_at timestamp without time zone);

insert into category (name, description) values ('PS5', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sollicitudin tempor id eu nisl nunc mi ipsum faucibus. Id faucibus nisl tincidunt eget nullam. Fermentum posuere urna nec tincidunt praesent semper feugiat nibh. Tortor vitae purus faucibus ornare. Risus nec feugiat in fermentum posuere urna nec tincidunt praesent. Enim praesent elementum facilisis leo. Pretium vulputate sapien nec sagittis. A pellentesque sit amet porttitor eget dolor morbi non. Etiam non quam lacus suspendisse faucibus interdum posuere lorem. Eu tincidunt tortor aliquam nulla facilisi cras. Erat imperdiet sed euismod nisi porta lorem mollis. Arcu felis bibendum ut tristique et. Id faucibus nisl tincidunt eget. Ipsum consequat nisl vel pretium lectus. Enim ut sem viverra aliquet eget sit amet.\nVitae proin sagittis nisl rhoncus mattis rhoncus urna neque. Blandit turpis cursus in hac habitasse platea. In nulla posuere sollicitudin aliquam ultrices. Habitasse platea dictumst vestibulum rhoncus. Sed egestas egestas fringilla phasellus faucibus scelerisque eleifend donec. In dictum non consectetur a erat nam at lectus urna. Elit sed vulputate mi sit amet mauris commodo quis. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper eget. Adipiscing bibendum est ultricies integer quis auctor elit sed. Feugiat scelerisque varius morbi enim nunc faucibus a. Nec sagittis aliquam malesuada bibendum arcu vitae elementum curabitur vitae. Scelerisque eleifend donec pretium vulputate sapien nec sagittis.');

insert into category (name, description) values ('XBOX Series X/S', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sollicitudin tempor id eu nisl nunc mi ipsum faucibus. Id faucibus nisl tincidunt eget nullam. Fermentum posuere urna nec tincidunt praesent semper feugiat nibh. Tortor vitae purus faucibus ornare. Risus nec feugiat in fermentum posuere urna nec tincidunt praesent. Enim praesent elementum facilisis leo. Pretium vulputate sapien nec sagittis. A pellentesque sit amet porttitor eget dolor morbi non. Etiam non quam lacus suspendisse faucibus interdum posuere lorem. Eu tincidunt tortor aliquam nulla facilisi cras. Erat imperdiet sed euismod nisi porta lorem mollis. Arcu felis bibendum ut tristique et. Id faucibus nisl tincidunt eget. Ipsum consequat nisl vel pretium lectus. Enim ut sem viverra aliquet eget sit amet.\nVitae proin sagittis nisl rhoncus mattis rhoncus urna neque. Blandit turpis cursus in hac habitasse platea. In nulla posuere sollicitudin aliquam ultrices. Habitasse platea dictumst vestibulum rhoncus. Sed egestas egestas fringilla phasellus faucibus scelerisque eleifend donec. In dictum non consectetur a erat nam at lectus urna. Elit sed vulputate mi sit amet mauris commodo quis. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper eget. Adipiscing bibendum est ultricies integer quis auctor elit sed. Feugiat scelerisque varius morbi enim nunc faucibus a. Nec sagittis aliquam malesuada bibendum arcu vitae elementum curabitur vitae. Scelerisque eleifend donec pretium vulputate sapien nec sagittis.');
